apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - protocol: TCP
      port: 5000         # Service port
      targetPort: 5000   # Container port
      nodePort: 30001    # Optional: fixed NodePort (Minikube will map this)
